<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.7" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.7" />
	</ItemGroup>

</Project>